import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Coregate",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div className='text-center bg-slate-800 p-8 my-6 rounded-md'>
        <Link href="/">
          <h1 className="text-3xl text-white font-bold">coregate.dev</h1>
        </Link>
        <p className='text-slate-300'>Just a little blog from an ordinary guy. 💻</p>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div className='border-t border-slate-500 mt-6 py-6 text-center text-slate-500'>
        <h3>
          Created by{" "}
          <Link href={"https://github.com/coregatekit"} className='text-blue-400'>coregatekit</Link>.
        </h3>
        <h3>This project is the result from learning with <Link href="https://www.youtube.com/watch?v=Hiabp1GY8fA" className='text-violet-400'>"pixegami"</Link>.</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body>
        <div className='mx-auto max-w-2xl px-6'>
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
