import './globals.css';
import Link from "next/link";

export const metadata = {
  title: "Coregate",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div>
        <Link href="/">
          <h1>Joe Kim's blog.</h1>
        </Link>
        <p>Welcome to my blog. 💻</p>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div>
        <br />
        <h3>
          Created by{" "}
          <Link href={"https://github.com/coregatekit"}>coregatekit</Link>.
        </h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
